apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"name":"test-stage-service"},"name":"test-stage-service","namespace":"test-stage"},"spec":{"ports":[{"name":"http","port":8080,"protocol":"TCP","targetPort":"http"}],"selector":{"app":"test-stage-nginx"},"type":"ClusterIP"}}
  creationTimestamp: null
  labels:
    name: test-stage-service
  name: test-stage-service
  selfLink: /api/v1/namespaces/test-stage/services/test-stage-service
spec:
  clusterIP: <unknown>
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: test-stage-nginx
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
