apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heapster-store
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: rook-block
