apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-alerts
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: rook-block
