apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: weave-scope-app-ingress
  namespace: kube-system
spec:
  rules:
  - host: lga-kube-test.pulsepoint.com
    http:
      paths:
      - backend:
          serviceName: weave-scope-app
          servicePort: 80
        path: /
