apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{"kubernetes.io/ingress.class":"nginx"},"name":"weave-scope-app-ingress","namespace":"kube-system"},"spec":{"rules":[{"host":"lga-kube.pulsepoint.com","http":{"paths":[{"backend":{"serviceName":"weave-scope-app","servicePort":80},"path":"/"}]}}]}}
    kubernetes.io/ingress.class: nginx
  creationTimestamp: null
  generation: 1
  name: weave-scope-app-ingress
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/ingresses/weave-scope-app-ingress
spec:
  rules:
  - host: lga-kube-test.pulsepoint.com
    http:
      paths:
      - backend:
          serviceName: weave-scope-app
          servicePort: 80
        path: /
status:
  loadBalancer: {}
