apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"name":"kube-public","namespace":""},"spec":{"finalizers":["kubernetes"]}}
  creationTimestamp: null
  name: kube-public
  selfLink: /api/v1/namespaces/kube-public
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
