---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: rook-ceph-mgr
    rook_cluster: rook
  name: rook-ceph-mgr1
  namespace: rook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rook-ceph-mgr
      rook_cluster: rook
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rook-ceph-mgr
        rook_cluster: rook
      name: rook-ceph-mgr1
    spec:
      containers:
      - args:
        - mgr
        - --config-dir=/var/lib/rook
        env:
        - name: ROOK_MGR_NAME
          value: rook-ceph-mgr1
        - name: ROOK_MGR_KEYRING
          valueFrom:
            secretKeyRef:
              key: keyring
              name: rook-ceph-mgr1
        - name: ROOK_PRIVATE_IPV4
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: ROOK_PUBLIC_IPV4
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: ROOK_CLUSTER_NAME
          value: rook
        - name: ROOK_MON_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              key: data
              name: rook-ceph-mon-endpoints
        - name: ROOK_MON_SECRET
          valueFrom:
            secretKeyRef:
              key: mon-secret
              name: rook-ceph-mon
        - name: ROOK_ADMIN_SECRET
          valueFrom:
            secretKeyRef:
              key: admin-secret
              name: rook-ceph-mon
        - name: ROOK_CEPH_CONFIG_OVERRIDE
          value: /etc/rook/config/override.conf
        image: rook/rook:v0.6.0
        imagePullPolicy: IfNotPresent
        name: rook-ceph-mgr1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/rook
          name: rook-data
        - mountPath: /etc/rook/config
          name: rook-config-override
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir:
          sizeLimit: "0"
        name: rook-data
      - configMap:
          defaultMode: 420
          items:
          - key: config
            path: override.conf
          name: rook-config-override
        name: rook-config-override
