apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: grafana-grafana
    chart: grafana-0.4.4
    component: grafana
    heritage: Tiller
    release: grafana
  name: grafana-grafana
  selfLink: /api/v1/namespaces/monitoring/services/grafana-grafana
spec:
  clusterIP: <unknown>
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana-grafana
    component: grafana
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
