apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana-grafana
    chart: grafana-0.4.4
    component: grafana
    heritage: Tiller
    release: grafana
  name: grafana-grafana
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana-grafana
    component: grafana
  sessionAffinity: None
  type: ClusterIP
