apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: prometheus
    chart: prometheus-4.5.0
    component: alertmanager
    heritage: Tiller
    release: prometheus
  name: prometheus-prometheus-alertmanager
  selfLink: /api/v1/namespaces/monitoring/services/prometheus-prometheus-alertmanager
spec:
  clusterIP: <unknown>
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9093
  selector:
    app: prometheus
    component: alertmanager
    release: prometheus
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
