apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"run":"kubernator"},"name":"kubernator","namespace":"kubernator"},"spec":{"replicas":1,"selector":{"matchLabels":{"run":"kubernator"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"run":"kubernator"}},"spec":{"containers":[{"image":"smpio/kubernator","imagePullPolicy":"Always","name":"kubernator","ports":[{"containerPort":80,"protocol":"TCP"}],"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","terminationGracePeriodSeconds":30}}}}
  creationTimestamp: null
  generation: 1
  labels:
    run: kubernator
  name: kubernator
  selfLink: /apis/extensions/v1beta1/namespaces/kubernator/deployments/kubernator
spec:
  replicas: 1
  selector:
    matchLabels:
      run: kubernator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: kubernator
    spec:
      containers:
      - image: smpio/kubernator
        imagePullPolicy: Always
        name: kubernator
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
