apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  creationTimestamp: 2018-01-03T00:02:07Z
  name: rook-api
  namespace: rook
  resourceVersion: "43565189"
  selfLink: /apis/rbac.authorization.k8s.io/v1beta1/namespaces/rook/roles/rook-api
  uid: 568bdd77-f019-11e7-926b-005056a8c8f3
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - secrets
  - pods
  - services
  - nodes
  - configmaps
  - events
  verbs:
  - get
  - list
  - watch
  - create
  - update
- apiGroups:
  - extensions
  resources:
  - thirdpartyresources
  - deployments
  - daemonsets
  - replicasets
  verbs:
  - get
  - list
  - create
  - delete
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - create
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
