apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  creationTimestamp: 2018-01-03T00:02:07Z
  name: rook-ceph-osd
  namespace: rook
  resourceVersion: "43565206"
  selfLink: /apis/rbac.authorization.k8s.io/v1beta1/namespaces/rook/roles/rook-ceph-osd
  uid: 5696b282-f019-11e7-926b-005056a8c8f3
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
