apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: traefik-ingress-controller
  selfLink: /api/v1/namespaces/ingress/serviceaccounts/traefik-ingress-controller
secrets:
- name: traefik-ingress-controller-token-fttv7
