apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /bh/metrics
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
    traefik.backend.circuitbreaker: NetworkErrorRatio() > 0.1 AND LatencyAtQuantileMS(50.0)
      > 10
    traefik.backend.loadbalancer.method: drr
    traefik.backend.loadbalancer.stickiness: "true"
  labels:
    name: bh-service
  name: bh-service
  namespace: qa
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: bh-app
  sessionAffinity: ClientIP
  type: ClusterIP
