apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: configuration-nginx
  selfLink: /api/v1/namespaces/qa/services/configuration-nginx
spec:
  clusterIP: <unknown>
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: configuration-nginx
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
