apiVersion: v1
kind: Service
metadata:
  labels:
    name: mock-server-service
  name: mock-server-service
  namespace: qa
spec:
  clusterIP: <unknown>
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: jmx
    port: 8686
    protocol: TCP
    targetPort: 8686
  selector:
    app: mock-server-app
  sessionAffinity: None
  type: ClusterIP
