apiVersion: v1
kind: Service
metadata:
  labels:
    name: test-runner-service
  name: test-runner-service
  namespace: qa
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: jmx
    port: 8686
    protocol: TCP
    targetPort: 8686
  selector:
    app: test-runner-app
  sessionAffinity: None
  type: ClusterIP
