apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  creationTimestamp: 2018-01-31T12:14:39Z
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    k8s-app: cluster-log-collector
    kubernetes.io/cluster-service: "true"
  name: cluster-log-collector
  resourceVersion: "51605630"
  selfLink: /apis/rbac.authorization.k8s.io/v1beta1/clusterroles/cluster-log-collector
  uid: 4fb0397b-0680-11e8-8246-005056a8c750
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - watch
  - list
