apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: rook-agent
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - secrets
  - configmaps
  - persistentvolumes
  - nodes
  - nodes/proxy
  verbs:
  - get
  - list
- apiGroups:
  - rook.io
  resources:
  - volumeattachments
  verbs:
  - get
  - list
  - create
  - delete
  - update
- apiGroups:
  - rook.io
  resources:
  - clusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
