apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1beta1","kind":"ClusterRole","metadata":{"annotations":{},"name":"rook-operator","namespace":""},"rules":[{"apiGroups":[""],"resources":["namespaces","serviceaccounts","secrets","pods","services","nodes","nodes/proxy","configmaps","events","persistentvolumes","persistentvolumeclaims"],"verbs":["get","list","watch","patch","create","update","delete"]},{"apiGroups":["extensions"],"resources":["thirdpartyresources","deployments","daemonsets","replicasets"],"verbs":["get","list","watch","create","delete"]},{"apiGroups":["apiextensions.k8s.io"],"resources":["customresourcedefinitions"],"verbs":["get","list","watch","create","delete"]},{"apiGroups":["rbac.authorization.k8s.io"],"resources":["clusterroles","clusterrolebindings","roles","rolebindings"],"verbs":["get","list","watch","create","update","delete"]},{"apiGroups":["storage.k8s.io"],"resources":["storageclasses"],"verbs":["get","list","watch","delete"]},{"apiGroups":["rook.io"],"resources":["*"],"verbs":["*"]}]}
  creationTimestamp: 2018-01-03T00:00:46Z
  name: rook-operator
  resourceVersion: "43564595"
  selfLink: /apis/rbac.authorization.k8s.io/v1beta1/clusterroles/rook-operator
  uid: 266b2228-f019-11e7-926b-005056a8c8f3
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - serviceaccounts
  - secrets
  - pods
  - services
  - nodes
  - nodes/proxy
  - configmaps
  - events
  - persistentvolumes
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
  - patch
  - create
  - update
  - delete
- apiGroups:
  - extensions
  resources:
  - thirdpartyresources
  - deployments
  - daemonsets
  - replicasets
  verbs:
  - get
  - list
  - watch
  - create
  - delete
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
  - create
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  - roles
  - rolebindings
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
  - delete
- apiGroups:
  - rook.io
  resources:
  - '*'
  verbs:
  - '*'
