apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: 2017-12-21T20:44:22Z
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:namespace-controller
  resourceVersion: "35066575"
  selfLink: /apis/rbac.authorization.k8s.io/v1beta1/clusterroles/system%3Acontroller%3Anamespace-controller
  uid: b9a4cca0-e68f-11e7-98cd-005056a8c750
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces/finalize
  - namespaces/status
  verbs:
  - update
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - delete
  - deletecollection
  - get
  - list
