apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: 2017-12-21T20:44:22Z
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:horizontal-pod-autoscaler
  resourceVersion: "35066573"
  selfLink: /apis/rbac.authorization.k8s.io/v1beta1/clusterroles/system%3Acontroller%3Ahorizontal-pod-autoscaler
  uid: b9a3b103-e68f-11e7-98cd-005056a8c750
rules:
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers/status
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - replicationcontrollers/scale
  verbs:
  - get
  - update
- apiGroups:
  - extensions
  resources:
  - replicationcontrollers/scale
  verbs:
  - get
  - update
- apiGroups:
  - apps
  - extensions
  resources:
  - deployments/scale
  - replicasets/scale
  verbs:
  - get
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
- apiGroups:
  - ""
  resourceNames:
  - 'http:heapster:'
  - 'https:heapster:'
  resources:
  - services
  verbs:
  - proxy
- apiGroups:
  - ""
  resourceNames:
  - 'http:heapster:'
  - 'https:heapster:'
  resources:
  - services/proxy
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
