apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: 2017-12-21T20:44:22Z
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:node-problem-detector
  resourceVersion: "35066556"
  selfLink: /apis/rbac.authorization.k8s.io/v1beta1/clusterroles/system%3Anode-problem-detector
  uid: b9985c11-e68f-11e7-98cd-005056a8c750
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
