apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: 2017-12-21T20:44:22Z
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:replication-controller
  resourceVersion: "35066580"
  selfLink: /apis/rbac.authorization.k8s.io/v1beta1/clusterroles/system%3Acontroller%3Areplication-controller
  uid: b9a91116-e68f-11e7-98cd-005056a8c750
rules:
- apiGroups:
  - ""
  resources:
  - replicationcontrollers
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - replicationcontrollers/status
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
