apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    app: test-runner-app
  name: test-runner-deployment
  namespace: qa
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: test-runner-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-runner-app
    spec:
      containers:
      - env:
        - name: DC
          valueFrom:
            configMapKeyRef:
              key: dc
              name: cluster-configs
        - name: CW_CONFIG_PREFIX
          valueFrom:
            configMapKeyRef:
              key: configPrefix
              name: cluster-configs
        - name: JAVA_OPTIONS
          valueFrom:
            configMapKeyRef:
              key: java.options
              name: test-runner-configs
        image: registry.pulsepoint.com/test-runner
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 30
          httpGet:
            path: /test-runner
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 90
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: test-runner-app
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8086
          name: jmx
          protocol: TCP
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /test-runner
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          limits:
            cpu: "4"
            memory: 4Gi
          requests:
            cpu: "4"
            memory: 3Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/jetty/start.ini
          name: start-ini
          subPath: start.ini.file
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: test-runner-configs
        name: start-ini