apiVersion: v1
data:
  config.yaml: |
    issuer: https://10.201.13.227:30554/dex
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      https: 0.0.0.0:5554
      tlsCert: /etc/dex/tls/apiserver.pem
      tlsKey: /etc/dex/tls/apiserver-key.pem
    connectors:
    - type: ldap
      name: PulsePoint
      id: ldap
      config:
        host: lga-cdc01.pulse.corp:3269
        insecureNoSSL: false
        #rootCA: /etc/dex/tls/pp_corp_ca.pem
        rootCA: /var/run/secrets/kubernetes.io/dex/pp_corp_ca.pem
        bindDN: $LDAP_LOGIN
        bindPW: $LDAP_PASSWORD
        userSearch:
          baseDN: OU=Users,OU=PulsePoint,dc=pulse,dc=corp
          filter: "(objectClass=user)"
          username: sAMAccountName
          idAttr: sAMAccountName
          emailAttr: mail
          nameAttr: sAMAccountName
        groupSearch:
          baseDN: OU=Groups,OU=PulsePoint,dc=pulse,dc=corp
          filter: "(objectClass=group)"
          userAttr: DN
          groupAttr: member
          nameAttr: cn
    oauth2:
      skipApprovalScreen: true

    staticClients:
    - id: internal-app
      redirectURIs:
      - 'https://10.201.13.227:30554/callback'
      - 'http://localhost/callback'
      name: 'Internal App'
      secret: ZXhhbXBsZS1hcHAtc2VjcmV1

    enablePasswordDB: false

    internalClient:
    # Used to create client redirect URL
      clientURL: https://10.201.13.227:30554/
      clientID: internal-app
      clientSecret: ZXhhbXBsZS1hcHAtc2VjcmV1
      rootCA: /etc/dex/tls/ca.pem
    # Used to access dex from client internally to get refresh and id tokens
      internalIssuerURL: https://10.201.13.227:30554/dex
      localUserName: ${USER}_lga-test
      localRootCA: ${HOME}/.kube/lga-test/ca.cert
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: dex
  selfLink: /api/v1/namespaces/kube-system/configmaps/dex
