apiVersion: v1
data:
  cni-conf.json: |
    {
      "name": "cbr0",
      "type": "flannel",
      "delegate": {
        "isDefaultGateway": true
      }
    }
  net-conf.json: |
    {
      "Network": "172.30.0.0/16",
      "Backend": {
        "Type": "vxlan"
      }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app: flannel
    tier: node
  name: kube-flannel-cfg
  selfLink: /api/v1/namespaces/kube-system/configmaps/kube-flannel-cfg
