apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    component: elasticsearch
    role: data
  name: storage-es-data-0
  namespace: logging
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
