apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"component":"elasticsearch","role":"master"},"name":"es-master","namespace":"logging"},"spec":{"progressDeadlineSeconds":600,"replicas":3,"revisionHistoryLimit":2,"selector":{"matchLabels":{"component":"elasticsearch","role":"master"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"pod.alpha.kubernetes.io/init-containers":"[{\"name\":\"sysctl\",\"image\":\"busybox\",\"command\":[\"sysctl\",\"-w\",\"vm.max_map_count=262144\"],\"resources\":{},\"terminationMessagePath\":\"/dev/termination-log\",\"terminationMessagePolicy\":\"File\",\"imagePullPolicy\":\"IfNotPresent\",\"securityContext\":{\"privileged\":true}}]","pod.beta.kubernetes.io/init-containers":"[{\"name\":\"sysctl\",\"image\":\"busybox\",\"command\":[\"sysctl\",\"-w\",\"vm.max_map_count=262144\"],\"resources\":{},\"terminationMessagePath\":\"/dev/termination-log\",\"terminationMessagePolicy\":\"File\",\"imagePullPolicy\":\"IfNotPresent\",\"securityContext\":{\"privileged\":true}}]"},"labels":{"component":"elasticsearch","role":"master"}},"spec":{"containers":[{"args":["-Ecluster.name=es-logging","-Enode.master=true","-Enode.data=false","-Enode.name=${NODE_NAME}","-Ehttp.enabled=true","-Ediscovery.zen.ping.unicast.hosts=elasticsearch-discovery.logging.svc.cluster.local","-Ediscovery.zen.minimum_master_nodes=2"],"command":["/run.sh"],"env":[{"name":"NODE_NAME","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.name"}}},{"name":"ES_JAVA_OPT","value":"-Des.cgroups.hierarchy.override=/ -Djava.net.preferIPv4Stack=true -Xms1G -Xmx1G"}],"image":"registry.pulsepoint.com/elasticsearch:5.5.1","imagePullPolicy":"Always","name":"es-master","ports":[{"containerPort":9300,"name":"transport","protocol":"TCP"}],"resources":{"limits":{"cpu":"1","memory":"3Gi"},"requests":{"cpu":"1","memory":"3Gi"}},"securityContext":{"capabilities":{"add":["IPC_LOCK","SYS_RESOURCE"]},"privileged":false},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/data","name":"storage"}]}],"dnsPolicy":"ClusterFirst","initContainers":[{"command":["sysctl","-w","vm.max_map_count=262144"],"image":"busybox","imagePullPolicy":"IfNotPresent","name":"sysctl","securityContext":{"privileged":true},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"restartPolicy":"Always","schedulerName":"default-scheduler","terminationGracePeriodSeconds":30,"volumes":[{"name":"storage"}]}}}}
  creationTimestamp: null
  generation: 1
  labels:
    component: elasticsearch
    role: master
  name: es-master
  selfLink: /apis/extensions/v1beta1/namespaces/logging/deployments/es-master
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      component: elasticsearch
      role: master
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        pod.alpha.kubernetes.io/init-containers: '[{"name":"sysctl","image":"busybox","command":["sysctl","-w","vm.max_map_count=262144"],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent","securityContext":{"privileged":true}}]'
        pod.beta.kubernetes.io/init-containers: '[{"name":"sysctl","image":"busybox","command":["sysctl","-w","vm.max_map_count=262144"],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent","securityContext":{"privileged":true}}]'
      creationTimestamp: null
      labels:
        component: elasticsearch
        role: master
    spec:
      containers:
      - args:
        - -Ecluster.name=es-logging
        - -Enode.master=true
        - -Enode.data=false
        - -Enode.name=${NODE_NAME}
        - -Ehttp.enabled=true
        - -Ediscovery.zen.ping.unicast.hosts=elasticsearch-discovery.logging.svc.cluster.local
        - -Ediscovery.zen.minimum_master_nodes=2
        command:
        - /run.sh
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: ES_JAVA_OPT
          value: -Des.cgroups.hierarchy.override=/ -Djava.net.preferIPv4Stack=true
            -Xms1G -Xmx1G
        image: registry.pulsepoint.com/elasticsearch:5.5.1
        imagePullPolicy: Always
        name: es-master
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 3Gi
          requests:
            cpu: "1"
            memory: 3Gi
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
            - SYS_RESOURCE
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: storage
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        image: busybox
        imagePullPolicy: IfNotPresent
        name: sysctl
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: storage
status: {}
