apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"component":"elasticsearch","role":"kibana"},"name":"kibana","namespace":"logging"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":2,"selector":{"matchLabels":{"component":"elasticsearch","role":"kibana"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"component":"elasticsearch","role":"kibana"}},"spec":{"containers":[{"args":["--cpu.cgroup.path.override=/","--cpuacct.cgroup.path.override=/","--elasticsearch.url=http://elasticsearch.logging.svc:9200","--server.host=0.0.0.0"],"command":["bin/kibana"],"image":"registry.pulsepoint.com/logging-kibana:5.5.1","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":5,"httpGet":{"path":"/","port":5601,"scheme":"HTTP"},"initialDelaySeconds":400,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":2},"name":"kibana","ports":[{"containerPort":5601,"name":"ui","protocol":"TCP"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/","port":5601,"scheme":"HTTP"},"initialDelaySeconds":200,"periodSeconds":30,"successThreshold":1,"timeoutSeconds":5},"resources":{"limits":{"cpu":"2","memory":"2Gi"},"requests":{"cpu":"2","memory":"2Gi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","terminationGracePeriodSeconds":30}}}}
  creationTimestamp: null
  generation: 1
  labels:
    component: elasticsearch
    role: kibana
  name: kibana
  selfLink: /apis/extensions/v1beta1/namespaces/logging/deployments/kibana
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      component: elasticsearch
      role: kibana
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        component: elasticsearch
        role: kibana
    spec:
      containers:
      - args:
        - --cpu.cgroup.path.override=/
        - --cpuacct.cgroup.path.override=/
        - --elasticsearch.url=http://elasticsearch.logging.svc:9200
        - --server.host=0.0.0.0
        command:
        - bin/kibana
        image: registry.pulsepoint.com/logging-kibana:5.5.1
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: 5601
            scheme: HTTP
          initialDelaySeconds: 400
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        name: kibana
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 5601
            scheme: HTTP
          initialDelaySeconds: 200
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "2"
            memory: 2Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
