---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    component: elasticsearch
    role: client
  name: es-client
  namespace: logging
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      component: elasticsearch
      role: client
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        pod.alpha.kubernetes.io/init-containers: '[{"name":"sysctl","image":"busybox","command":["sysctl","-w","vm.max_map_count=262144"],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent","securityContext":{"privileged":true}}]'
        pod.beta.kubernetes.io/init-containers: '[{"name":"sysctl","image":"busybox","command":["sysctl","-w","vm.max_map_count=262144"],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent","securityContext":{"privileged":true}}]'
      labels:
        component: elasticsearch
        role: client
    spec:
      containers:
      - args:
        - -Ecluster.name=es-logging
        - -Enode.master=false
        - -Enode.data=false
        - -Enode.name=${NODE_NAME}
        - -Ehttp.enabled=true
        - -Ediscovery.zen.ping.unicast.hosts=elasticsearch-discovery.logging.svc.cluster.local
        - -Ediscovery.zen.minimum_master_nodes=2
        command:
        - /run.sh
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: ES_JAVA_OPTS
          value: -Djava.net.preferIPv4Stack=true -Xms1G -Xmx1G -Des.cgroups.hierarchy.override=/
        - name: ES_JAVA_OPT
          value: -Djava.net.preferIPv4Stack=true -Xms1G -Xmx1G -Des.cgroups.hierarchy.override=/
        image: registry.pulsepoint.com/elasticsearch:5.5.1
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 600
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: es-client
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 3Gi
          requests:
            cpu: 100m
            memory: 3Gi
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
            - SYS_RESOURCE
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: storage
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        image: busybox
        imagePullPolicy: IfNotPresent
        name: sysctl
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: storage
