apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    component: apiserver
    provider: kubernetes
  name: kubernetes
  selfLink: /api/v1/namespaces/default/services/kubernetes
spec:
  clusterIP: <unknown>
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: kubernetes
    component: apiserver
  sessionAffinity: ClientIP
  type: ClusterIP
status:
  loadBalancer: {}
