apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"flux","namespace":"cicd"},"spec":{"ports":[{"nodePort":30303,"port":80,"targetPort":3030}],"selector":{"name":"flux"},"type":"NodePort"}}
  creationTimestamp: null
  name: flux
  selfLink: /api/v1/namespaces/cicd/services/flux
spec:
  clusterIP: <unknown>
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3030
  selector:
    name: flux
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
