apiVersion: v1
kind: Service
metadata:
  name: flux
  namspace: cicd
spec:
  clusterIP: <unknown>
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3030
  selector:
    name: flux
  sessionAffinity: None
  type: NodePort
