apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins-jenkins
    chart: jenkins-0.13.0
    component: jenkins-jenkins-master
  name: jenkins-jenkins-agent
  namspace: cicd
spec:
  clusterIP: <unknown>
  ports:
  - name: slavelistener
    port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    component: jenkins-jenkins-master
  sessionAffinity: None
  type: ClusterIP
