apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins-jenkins
    chart: jenkins-0.13.0
    component: jenkins-jenkins-master
    heritage: Tiller
    release: jenkins
  name: jenkins-jenkins
  namespace: cicd
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    component: jenkins-jenkins-master
  sessionAffinity: None
  type: ClusterIP
