apiVersion: v1
kind: Service
metadata:
  name: memcached
  namespace: cicd
spec:
  clusterIP: None
  ports:
  - name: memcached
    port: 11211
    protocol: TCP
    targetPort: 11211
  selector:
    name: memcached
  sessionAffinity: None
  type: ClusterIP
