apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"memcached","namespace":"cicd"},"spec":{"clusterIP":"None","ports":[{"name":"memcached","port":11211}],"selector":{"name":"memcached"}}}
  creationTimestamp: null
  name: memcached
  selfLink: /api/v1/namespaces/cicd/services/memcached
spec:
  clusterIP: None
  ports:
  - name: memcached
    port: 11211
    protocol: TCP
    targetPort: 11211
  selector:
    name: memcached
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
