apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    app: a10bridge-app
  name: a10bridge-deployment
  namespace: ingress
spec:
  minReadySeconds: 5
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 20
  selector:
    matchLabels:
      app: a10bridge-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: a10bridge-app
    spec:
      containers:
      - args:
        - -a10-config=/etc/a10bridge/config.yaml
        - -daemon
        - -logtostderr
        env:
        - name: INTERVAL
          valueFrom:
            configMapKeyRef:
              key: interval
              name: a10-config
        - name: A10PWD
          valueFrom:
            secretKeyRef:
              key: password
              name: a10secret
        image: registry.pulsepoint.com/a10bridge:0.4
        imagePullPolicy: Always
        name: a10bridge-app
        resources:
          limits:
            cpu: 2m
            memory: 20Mi
          requests:
            cpu: 1m
            memory: 10Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/a10bridge/config.yaml
          name: configs
          subPath: config.yaml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: a10-bridge
      serviceAccountName: a10-bridge
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: a10-config
        name: configs
