apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    app: rook-operator
  name: rook-operator
  namespace: rook
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rook-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rook-operator
    spec:
      containers:
      - args:
        - operator
        env:
        - name: ROOK_REPO_PREFIX
          value: rook
        - name: ROOK_MON_HEALTHCHECK_INTERVAL
          value: 20s
        - name: ROOK_MON_OUT_TIMEOUT
          value: 300s
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: rook/rook:v0.6.0
        imagePullPolicy: IfNotPresent
        name: rook-operator
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: rook-operator
      serviceAccountName: rook-operator
      terminationGracePeriodSeconds: 30
