apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins
  namespace: cicd
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: rook-block
