apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"name":"test-stage","namespace":""},"spec":{"finalizers":["kubernetes"]}}
  creationTimestamp: null
  name: test-stage
  selfLink: /api/v1/namespaces/test-stage
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
