apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"rook-operator","namespace":"rook"}}
  creationTimestamp: null
  name: rook-operator
  selfLink: /api/v1/namespaces/rook/serviceaccounts/rook-operator
secrets:
- name: rook-operator-token-hw0vx
