---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: memcached
  name: memcached
  namespace: cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      name: memcached
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: memcached
    spec:
      containers:
      - args:
        - -m 64
        - -p 11211
        - -vv
        image: memcached:1.4.25
        imagePullPolicy: IfNotPresent
        name: memcached
        ports:
        - containerPort: 11211
          name: clients
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
