apiVersion: v1
data:
  traefik.toml: "# traefik.toml\nlogLevel = \"INFO\"\ndefaultEntryPoints = [\"http\"]\n[entryPoints]\n
    \ [entryPoints.http]\n  address = \":80\"\n  compress = true\n[web]\n  address
    = \":18080\"      \n[kubernetes]\n"
kind: ConfigMap
metadata:
  labels:
    app: traefik-ingress
  name: traefik-ingress-controller-80
  namespace: ingress