apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  creationTimestamp: 2018-01-03T00:02:07Z
  name: rook-api
  namespace: rook
  resourceVersion: "43565190"
  selfLink: /apis/rbac.authorization.k8s.io/v1beta1/namespaces/rook/rolebindings/rook-api
  uid: 568d3199-f019-11e7-926b-005056a8c8f3
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rook-api
subjects:
- kind: ServiceAccount
  name: rook-api
  namespace: rook
