apiVersion: v1
data:
  config: "[global]\n# writing two copies for redundancy\nosd pool default size =
    2\n# allow writing one copy in a degraded state\nosd pool default min size = 1
    \n# 4 osds * 100 divided by 2 replicas\nosd pool default pg num = 200\n# needs
    to be the same as the above\nosd pool default pgp num = 200\n"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"config":"[global]\n# writing two copies for redundancy\nosd pool default size = 2\n# allow writing one copy in a degraded state\nosd pool default min size = 1 \n# 4 osds * 100 divided by 2 replicas\nosd pool default pg num = 200\n# needs to be the same as the above\nosd pool default pgp num = 200\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"rook-config-override","namespace":"rook"}}
  creationTimestamp: null
  name: rook-config-override
  selfLink: /api/v1/namespaces/rook/configmaps/rook-config-override
