apiVersion: v1
data:
  bluefs: |
    1
  ceph_fsid: |
    368dbe0d-333c-4287-bc58-f25a49e8d053
  fsid: |
    07fde5b4-8245-43b3-bff6-09de4c45c8d0
  kv_backend: |
    rocksdb
  magic: |
    ceph osd volume v026
  mkfs_done: |
    yes
  ready: |
    ready
  type: |
    bluestore
  whoami: |
    2
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: rook-ceph-osd-2-fs-backup
  selfLink: /api/v1/namespaces/rook/configmaps/rook-ceph-osd-2-fs-backup
