apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"DaemonSet","metadata":{"annotations":{},"labels":{"app":"rook-agent"},"name":"rook-agent","namespace":"rook"},"spec":{"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"rook-agent"}},"template":{"metadata":{"labels":{"app":"rook-agent"}},"spec":{"containers":[{"args":["agent"],"env":[{"name":"POD_NAMESPACE","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.namespace"}}},{"name":"NODE_NAME","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"spec.nodeName"}}}],"image":"rook/rook:v0.6.0","imagePullPolicy":"IfNotPresent","name":"rook-agent","securityContext":{"privileged":true},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/flexmnt","name":"flexvolume"},{"mountPath":"/dev","name":"dev"},{"mountPath":"/sys","name":"sys"},{"mountPath":"/lib/modules","name":"libmodules"},{"mountPath":"/sbin/modprobe","name":"modprobe"},{"mountPath":"/sbin/modinfo","name":"modinfo"}]}],"dnsPolicy":"ClusterFirst","hostNetwork":true,"restartPolicy":"Always","schedulerName":"default-scheduler","serviceAccount":"rook-agent","serviceAccountName":"rook-agent","terminationGracePeriodSeconds":30,"volumes":[{"hostPath":{"path":"/usr/libexec/kubernetes/kubelet-plugins/volume/exec/"},"name":"flexvolume"},{"hostPath":{"path":"/dev"},"name":"dev"},{"hostPath":{"path":"/sys"},"name":"sys"},{"hostPath":{"path":"/lib/modules"},"name":"libmodules"},{"hostPath":{"path":"/sbin/modprobe"},"name":"modprobe"},{"hostPath":{"path":"/sbin/modinfo"},"name":"modinfo"}]}},"templateGeneration":1,"updateStrategy":{"type":"OnDelete"}}}
  creationTimestamp: null
  generation: 1
  labels:
    app: rook-agent
  name: rook-agent
  selfLink: /apis/extensions/v1beta1/namespaces/rook/daemonsets/rook-agent
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rook-agent
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rook-agent
    spec:
      containers:
      - args:
        - agent
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: rook/rook:v0.6.0
        imagePullPolicy: IfNotPresent
        name: rook-agent
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /flexmnt
          name: flexvolume
        - mountPath: /dev
          name: dev
        - mountPath: /sys
          name: sys
        - mountPath: /lib/modules
          name: libmodules
        - mountPath: /sbin/modprobe
          name: modprobe
        - mountPath: /sbin/modinfo
          name: modinfo
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: rook-agent
      serviceAccountName: rook-agent
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/
        name: flexvolume
      - hostPath:
          path: /dev
        name: dev
      - hostPath:
          path: /sys
        name: sys
      - hostPath:
          path: /lib/modules
        name: libmodules
      - hostPath:
          path: /sbin/modprobe
        name: modprobe
      - hostPath:
          path: /sbin/modinfo
        name: modinfo
  templateGeneration: 1
  updateStrategy:
    type: OnDelete
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
