apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: es-ingress-nginx
  namespace: logging
spec:
  rules:
  - host: es.logging.pulse.com
    http:
      paths:
      - backend:
          serviceName: elasticsearch
          servicePort: http
        path: /
