apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: kibana-ingress-nginx
  namespace: logging
spec:
  rules:
  - host: lga-kube-kibana
    http:
      paths:
      - backend:
          serviceName: kibana
          servicePort: ui
        path: /
  - host: lga-kube-kibana.pulsepoint.com
    http:
      paths:
      - backend:
          serviceName: kibana
          servicePort: ui
        path: /
