apiVersion: v1
data:
  run.sh: |-
    @test "Testing Jenkins UI is accessible" {
      curl --retry 24 --retry-delay 10 jenkins-jenkins:8080/login
    }
kind: ConfigMap
metadata:
  name: jenkins-jenkins-tests
  namespace: cicd
