---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    cloud.weave.works/launcher-info: |-
      {
        "server-version": "master-938237c",
        "original-request": {
          "url": "/k8s/v1.7/scope.yaml?k8s-version=Q2xpZW50IFZlcnNpb246IHZlcnNpb24uSW5mb3tNYWpvcjoiMSIsIE1pbm9yOiI3IiwgR2l0VmVyc2lvbjoidjEuNy40IiwgR2l0Q29tbWl0OiI3OTM2NThmMmQ3Y2E3ZjA2NGQyYmRmNjA2NTE5ZjlmZTEyMjljMzgxIiwgR2l0VHJlZVN0YXRlOiJjbGVhbiIsIEJ1aWxkRGF0ZToiMjAxNy0wOC0xN1QwODo0ODoyM1oiLCBHb1ZlcnNpb246ImdvMS44LjMiLCBDb21waWxlcjoiZ2MiLCBQbGF0Zm9ybToibGludXgvYW1kNjQifQpTZXJ2ZXIgVmVyc2lvbjogdmVyc2lvbi5JbmZve01ham9yOiIxIiwgTWlub3I6IjciLCBHaXRWZXJzaW9uOiJ2MS43LjExIiwgR2l0Q29tbWl0OiJiMTNmMmZkNjgyZDU2ZWFiN2E2YTJiNWExY2FiMWEzZDJjOGJkZDU1IiwgR2l0VHJlZVN0YXRlOiJjbGVhbiIsIEJ1aWxkRGF0ZToiMjAxNy0xMS0yNVQxNzo1MTozOVoiLCBHb1ZlcnNpb246ImdvMS44LjMiLCBDb21waWxlcjoiZ2MiLCBQbGF0Zm9ybToibGludXgvYW1kNjQifQo=",
          "date": "Wed Jan 10 2018 03:23:58 GMT+0000 (UTC)"
        },
        "email-address": "support@weave.works"
      }
  labels:
    app: weave-scope
    name: weave-scope-app
    weave-cloud-component: scope
    weave-scope-component: app
  name: weave-scope-app
  namespace: kube-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: weave-scope
      name: weave-scope-app
      weave-cloud-component: scope
      weave-scope-component: app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: weave-scope
        name: weave-scope-app
        weave-cloud-component: scope
        weave-scope-component: app
    spec:
      containers:
      - args:
        - --no-probe
        image: weaveworks/scope:1.6.7
        imagePullPolicy: IfNotPresent
        name: app
        ports:
        - containerPort: 4040
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
