apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1beta1","kind":"ClusterRoleBinding","metadata":{"annotations":{},"name":"kube-dns","namespace":""},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"system:kube-dns"},"subjects":[{"kind":"ServiceAccount","name":"kube-dns","namespace":"kube-system"}]}
  creationTimestamp: 2018-01-05T20:20:28Z
  name: kube-dns
  resourceVersion: "48786915"
  selfLink: /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/kube-dns
  uid: df40fe60-f255-11e7-91f9-005056a8c8f3
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kube-dns
subjects:
- kind: ServiceAccount
  name: kube-dns
  namespace: kube-system
