apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: pp:view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pp:view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated
