apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: 2017-12-21T20:44:23Z
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:statefulset-controller
  resourceVersion: "35066621"
  selfLink: /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system%3Acontroller%3Astatefulset-controller
  uid: b9ffded7-e68f-11e7-98cd-005056a8c750
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:controller:statefulset-controller
subjects:
- kind: ServiceAccount
  name: statefulset-controller
  namespace: kube-system
