apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: 2017-12-21T20:44:23Z
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:pod-garbage-collector
  resourceVersion: "35066612"
  selfLink: /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system%3Acontroller%3Apod-garbage-collector
  uid: b9d5324d-e68f-11e7-98cd-005056a8c750
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:controller:pod-garbage-collector
subjects:
- kind: ServiceAccount
  name: pod-garbage-collector
  namespace: kube-system
