apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rook-api
    rook_cluster: rook
  name: rook-api
  selfLink: /api/v1/namespaces/rook/services/rook-api
spec:
  clusterIP: <unknown>
  ports:
  - name: rook-api
    port: 8124
    protocol: TCP
    targetPort: 8124
  selector:
    app: rook-api
    rook_cluster: rook
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
