apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","kubernetes.io/cluster-service":"true"},"name":"node-problem-detector","namespace":"kube-system"}}
  creationTimestamp: null
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/cluster-service: "true"
  name: node-problem-detector
  selfLink: /api/v1/namespaces/kube-system/serviceaccounts/node-problem-detector
secrets:
- name: node-problem-detector-token-777jh
