apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: elasticsearch-discovery
  selfLink: /api/v1/namespaces/logging/services/elasticsearch-discovery
spec:
  clusterIP: <unknown>
  ports:
  - name: transport
    port: 9300
    protocol: TCP
    targetPort: 9300
  selector:
    component: elasticsearch
    role: master
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
