apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-discovery
  namespace: logging
spec:
  ports:
  - name: transport
    port: 9300
    protocol: TCP
    targetPort: 9300
  selector:
    component: elasticsearch
    role: master
  sessionAffinity: None
  type: ClusterIP
