apiVersion: v1
kind: Service
metadata:
  labels:
    component: elasticsearch
    role: data
  name: elasticsearch-data
  namespace: logging
spec:
  clusterIP: None
  ports:
  - name: transport
    port: 9300
    protocol: TCP
    targetPort: 9300
  selector:
    component: elasticsearch
    role: data
  sessionAffinity: None
  type: ClusterIP
