apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    component: elasticsearch
    role: data
  name: elasticsearch-data
  selfLink: /api/v1/namespaces/logging/services/elasticsearch-data
spec:
  clusterIP: None
  ports:
  - name: transport
    port: 9300
    protocol: TCP
    targetPort: 9300
  selector:
    component: elasticsearch
    role: data
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
