apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    component: elasticsearch
    role: client
  name: elasticsearch
  selfLink: /api/v1/namespaces/logging/services/elasticsearch
spec:
  clusterIP: <unknown>
  ports:
  - name: http
    port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    component: elasticsearch
    role: client
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
