apiVersion: v1
kind: Service
metadata:
  labels:
    component: elasticsearch
    role: client
  name: elasticsearch
  namespace: logging
spec:
  clusterIP: <unknown>
  ports:
  - name: http
    port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    component: elasticsearch
    role: client
  sessionAffinity: None
  type: ClusterIP
