apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: logging
spec:
  ports:
  - name: ui
    port: 5601
    protocol: TCP
    targetPort: ui
  selector:
    component: elasticsearch
    role: kibana
  sessionAffinity: None
  type: ClusterIP
