apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: kibana
  selfLink: /api/v1/namespaces/logging/services/kibana
spec:
  clusterIP: <unknown>
  ports:
  - name: ui
    port: 5601
    protocol: TCP
    targetPort: ui
  selector:
    component: elasticsearch
    role: kibana
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
