apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"test-stage-nginx"},"name":"test-stage-nginx","namespace":"test-stage"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":2,"selector":{"matchLabels":{"app":"test-stage-nginx"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"labels":{"app":"test-stage-nginx"}},"spec":{"containers":[{"image":"nginx","imagePullPolicy":"Always","name":"nginx","ports":[{"containerPort":80,"name":"http","protocol":"TCP"}],"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/usr/share/nginx/html","name":"web"},{"mountPath":"/var/lib/containers/my_mem_mount2","name":"test-ed"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","terminationGracePeriodSeconds":30,"volumes":[{"configMap":{"defaultMode":420,"name":"test-stage-config"},"name":"web"},{"emptyDir":{"medium":"Memory"},"name":"test-ed"}]}}}}
  creationTimestamp: null
  generation: 1
  labels:
    app: test-stage-nginx
  name: test-stage-nginx
  selfLink: /apis/extensions/v1beta1/namespaces/test-stage/deployments/test-stage-nginx
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: test-stage-nginx
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-stage-nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: web
        - mountPath: /var/lib/containers/my_mem_mount2
          name: test-ed
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: test-stage-config
        name: web
      - emptyDir:
          medium: Memory
        name: test-ed
status: {}
