apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{"kubernetes.io/ingress.class":"traefik"},"name":"bh-ingress-traefik","namespace":"bh"},"spec":{"rules":[{"host":"bh.contextweb.com","http":{"paths":[{"backend":{"serviceName":"bh-service","servicePort":8080},"path":"/"}]}},{"host":"bh.lga.contextweb.com","http":{"paths":[{"backend":{"serviceName":"bh-service","servicePort":8080},"path":"/"}]}},{"http":{"paths":[{"backend":{"serviceName":"bh-service","servicePort":8080},"path":"/bh/"}]}}]}}
    kubernetes.io/ingress.class: traefik
  creationTimestamp: null
  generation: 1
  name: bh-ingress-traefik
  selfLink: /apis/extensions/v1beta1/namespaces/bh/ingresses/bh-ingress-traefik
spec:
  backend:
    serviceName: default-http-backend
    servicePort: 80
  rules:
  - host: bh.contextweb.com
    http:
      paths:
      - backend:
          serviceName: bh-service
          servicePort: 8080
        path: /
  - host: bh.lga.contextweb.com
    http:
      paths:
      - backend:
          serviceName: bh-service
          servicePort: 8080
        path: /
  - http:
      paths:
      - backend:
          serviceName: bh-service
          servicePort: 8080
        path: /bh/
status:
  loadBalancer: {}
