apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"DaemonSet","metadata":{"annotations":{},"labels":{"app":"kafka-message-producer-app"},"name":"kafka-message-producer-ds","namespace":"kafka-message-producer"},"spec":{"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"kafka-message-producer-app"}},"template":{"metadata":{"annotations":{"pod.alpha.kubernetes.io/init-containers":"[{\"name\":\"chmod-kmp-dir\",\"image\":\"busybox\",\"command\":[\"sh\",\"-c\",\"chown -R 100:101 /var/log/pulsepoint/wide\"],\"resources\":{},\"volumeMounts\":[{\"name\":\"kafka-logs\",\"mountPath\":\"/var/log/pulsepoint/wide\"}],\"terminationMessagePath\":\"/dev/termination-log\",\"terminationMessagePolicy\":\"File\",\"imagePullPolicy\":\"Always\",\"securityContext\":{\"runAsUser\":0}}]","pod.beta.kubernetes.io/init-containers":"[{\"name\":\"chmod-kmp-dir\",\"image\":\"busybox\",\"command\":[\"sh\",\"-c\",\"chown -R 100:101 /var/log/pulsepoint/wide\"],\"resources\":{},\"volumeMounts\":[{\"name\":\"kafka-logs\",\"mountPath\":\"/var/log/pulsepoint/wide\"}],\"terminationMessagePath\":\"/dev/termination-log\",\"terminationMessagePolicy\":\"File\",\"imagePullPolicy\":\"Always\",\"securityContext\":{\"runAsUser\":0}}]"},"labels":{"app":"kafka-message-producer-app"}},"spec":{"containers":[{"env":[{"name":"FLUENTD_ARGS","value":"--no-supervisor -q"},{"name":"KUB_NAMESPACE","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.namespace"}}},{"name":"KUB_NODE","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"spec.nodeName"}}},{"name":"CLUSTER_NAME","valueFrom":{"configMapKeyRef":{"key":"name","name":"cluster-configs"}}},{"name":"CONFIG_ENV","valueFrom":{"configMapKeyRef":{"key":"env","name":"env-configs"}}},{"name":"CONFIG_DC","valueFrom":{"configMapKeyRef":{"key":"dc","name":"cluster-configs"}}}],"image":"registry.pulsepoint.com/logging-fluentd:kub_cluster","imagePullPolicy":"Always","name":"fluentd","ports":[{"containerPort":5170,"name":"fluentd","protocol":"TCP"}],"resources":{"requests":{"cpu":"100m"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/fluentd/etc/fluent.conf","name":"kafka-message-producer-configs","subPath":"fluentd.options"}]},{"env":[{"name":"DC","valueFrom":{"configMapKeyRef":{"key":"dc","name":"cluster-configs"}}},{"name":"JAVA_OPTIONS","valueFrom":{"configMapKeyRef":{"key":"java.options","name":"kafka-message-producer-configs"}}},{"name":"CONFIG_LINK","valueFrom":{"configMapKeyRef":{"key":"configPrefix","name":"cluster-configs"}}},{"name":"CONFIG_ENV","valueFrom":{"configMapKeyRef":{"key":"configEnvironment","name":"env-configs"}}},{"name":"CW_CONFIG_PREFIX","value":"$(CONFIG_LINK)$(CONFIG_ENV)"},{"name":"CW_CONFIG_LOG4J","value":"$(CONFIG_LINK)$(CONFIG_ENV)/batch/kafka-message-producer/2/log4j2-kube.xml"}],"image":"registry.pulsepoint.com/kafka-message-producer:ET-3111","imagePullPolicy":"IfNotPresent","livenessProbe":{"exec":{"command":["rm","/tmp/kmp-alive"]},"failureThreshold":10,"periodSeconds":400,"successThreshold":1,"timeoutSeconds":1},"name":"kafka-message-producer-app","resources":{"limits":{"cpu":"200m","memory":"250Mi"},"requests":{"cpu":"100m","memory":"120Mi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/var/log/pulsepoint/wide","name":"kafka-logs"}]}],"dnsPolicy":"ClusterFirst","initContainers":[{"command":["sh","-c","chown -R 100:101 /var/log/pulsepoint/wide"],"image":"busybox","imagePullPolicy":"Always","name":"chmod-kmp-dir","securityContext":{"runAsUser":0},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/var/log/pulsepoint/wide","name":"kafka-logs"}]}],"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{"fsGroup":101,"runAsUser":100},"terminationGracePeriodSeconds":30,"volumes":[{"configMap":{"defaultMode":420,"name":"kafka-message-producer-configs"},"name":"prometheus-yaml"},{"configMap":{"defaultMode":420,"name":"kafka-message-producer-configs"},"name":"kafka-message-producer-configs"},{"hostPath":{"path":"/var/log/pulsepoint/wide"},"name":"kafka-logs"}]}},"templateGeneration":4,"updateStrategy":{"rollingUpdate":{"maxUnavailable":"100%"},"type":"RollingUpdate"}}}
  creationTimestamp: null
  generation: 1
  labels:
    app: kafka-message-producer-app
  name: kafka-message-producer-ds
  selfLink: /apis/extensions/v1beta1/namespaces/kafka-message-producer/daemonsets/kafka-message-producer-ds
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kafka-message-producer-app
  template:
    metadata:
      annotations:
        pod.alpha.kubernetes.io/init-containers: '[{"name":"chmod-kmp-dir","image":"busybox","command":["sh","-c","chown
          -R 100:101 /var/log/pulsepoint/wide"],"resources":{},"volumeMounts":[{"name":"kafka-logs","mountPath":"/var/log/pulsepoint/wide"}],"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"Always","securityContext":{"runAsUser":0}}]'
        pod.beta.kubernetes.io/init-containers: '[{"name":"chmod-kmp-dir","image":"busybox","command":["sh","-c","chown
          -R 100:101 /var/log/pulsepoint/wide"],"resources":{},"volumeMounts":[{"name":"kafka-logs","mountPath":"/var/log/pulsepoint/wide"}],"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"Always","securityContext":{"runAsUser":0}}]'
      creationTimestamp: null
      labels:
        app: kafka-message-producer-app
    spec:
      containers:
      - env:
        - name: FLUENTD_ARGS
          value: --no-supervisor -q
        - name: KUB_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: KUB_NODE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              key: name
              name: cluster-configs
        - name: CONFIG_ENV
          valueFrom:
            configMapKeyRef:
              key: env
              name: env-configs
        - name: CONFIG_DC
          valueFrom:
            configMapKeyRef:
              key: dc
              name: cluster-configs
        image: registry.pulsepoint.com/logging-fluentd:kub_cluster
        imagePullPolicy: Always
        name: fluentd
        ports:
        - containerPort: 5170
          name: fluentd
          protocol: TCP
        resources:
          requests:
            cpu: 100m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /fluentd/etc/fluent.conf
          name: kafka-message-producer-configs
          subPath: fluentd.options
      - env:
        - name: DC
          valueFrom:
            configMapKeyRef:
              key: dc
              name: cluster-configs
        - name: JAVA_OPTIONS
          valueFrom:
            configMapKeyRef:
              key: java.options
              name: kafka-message-producer-configs
        - name: CONFIG_LINK
          valueFrom:
            configMapKeyRef:
              key: configPrefix
              name: cluster-configs
        - name: CONFIG_ENV
          valueFrom:
            configMapKeyRef:
              key: configEnvironment
              name: env-configs
        - name: CW_CONFIG_PREFIX
          value: $(CONFIG_LINK)$(CONFIG_ENV)
        - name: CW_CONFIG_LOG4J
          value: $(CONFIG_LINK)$(CONFIG_ENV)/batch/kafka-message-producer/2/log4j2-kube.xml
        image: registry.pulsepoint.com/kafka-message-producer:ET-3111
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - rm
            - /tmp/kmp-alive
          failureThreshold: 10
          periodSeconds: 400
          successThreshold: 1
          timeoutSeconds: 1
        name: kafka-message-producer-app
        resources:
          limits:
            cpu: 200m
            memory: 250Mi
          requests:
            cpu: 100m
            memory: 120Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/log/pulsepoint/wide
          name: kafka-logs
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - chown -R 100:101 /var/log/pulsepoint/wide
        image: busybox
        imagePullPolicy: Always
        name: chmod-kmp-dir
        resources: {}
        securityContext:
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/log/pulsepoint/wide
          name: kafka-logs
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 101
        runAsUser: 100
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: kafka-message-producer-configs
        name: prometheus-yaml
      - configMap:
          defaultMode: 420
          name: kafka-message-producer-configs
        name: kafka-message-producer-configs
      - hostPath:
          path: /var/log/pulsepoint/wide
        name: kafka-logs
  templateGeneration: 4
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 100%
    type: RollingUpdate
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
