apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  annotations:
  name: a10-bridge-role-binding
  namespace: ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: a10-bridge-role
subjects:
- kind: ServiceAccount
  name: a10-bridge
  namespace: ingress
