apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"name":"kafka-message-producer","namespace":""},"spec":{"finalizers":["kubernetes"]}}
  creationTimestamp: null
  name: kafka-message-producer
  selfLink: /api/v1/namespaces/kafka-message-producer
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
