apiVersion: v1
kind: Service
metadata:
  name: configuration-nginx
  naemspace: staging
spec:
  clusterIP: <unknown>
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: configuration-nginx
  sessionAffinity: None
  type: ClusterIP
