apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: dex
  name: dex
  namespace: kube-system
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dex
  template:
    metadata:
      labels:
        app: dex
    spec:
      containers:
      - command:
        - /usr/local/bin/dex
        - serve
        - /etc/dex/cfg/config.yaml
        env:
        - name: LDAP_LOGIN
          valueFrom:
            secretKeyRef:
              key: login
              name: pp-ldap
        - name: LDAP_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: pp-ldap
        image: registry.pulsepoint.com/dex:pp
        imagePullPolicy: Always
        name: dex
        ports:
        - containerPort: 5554
          name: https
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/dex/cfg
          name: config
        - mountPath: /etc/dex/tls
          name: ssl-certs-kubernetes
          readOnly: true
        - mountPath: /var/run/secrets/kubernetes.io/dex
          name: pp-ldap-secret
          readOnly: true
      dnsPolicy: ClusterFirst
      nodeSelector:
        dex: "true"
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: dex
      serviceAccountName: dex
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: config.yaml
            path: config.yaml
          name: dex
        name: config
      - name: pp-ldap-secret
        secret:
          defaultMode: 420
          secretName: pp-ldap
      - hostPath:
          path: /etc/kubernetes/ssl
        name: ssl-certs-kubernetes
  templateGeneration: 2
  updateStrategy:
    type: OnDelete
