apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    k8s-app: node-problem-detector
    kubernetes.io/cluster-service: "true"
    version: v0.1
  name: node-problem-detector-v0.1
  namespace: kube-system
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: node-problem-detector
      kubernetes.io/cluster-service: "true"
      version: v0.1
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: node-problem-detector
        kubernetes.io/cluster-service: "true"
        version: v0.1
    spec:
      containers:
      - image: gcr.io/google_containers/node-problem-detector:v0.1
        imagePullPolicy: IfNotPresent
        name: node-problem-detector
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 20m
            memory: 20Mi
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /log
          name: log
          readOnly: true
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: node-problem-detector
      serviceAccountName: node-problem-detector
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /var/log/
        name: log
  templateGeneration: 1
  updateStrategy:
    type: OnDelete
