apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"name":"flux"},"name":"flux","namespace":"cicd"},"spec":{"replicas":1,"selector":{"matchLabels":{"name":"flux"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"labels":{"name":"flux"}},"spec":{"containers":[{"args":["--git-url=git@github.com:jdrahos/kube-manifests.git","--git-branch=lga-test"],"image":"quay.io/weaveworks/flux:1.2.3","imagePullPolicy":"IfNotPresent","name":"flux","ports":[{"containerPort":3030,"protocol":"TCP"}],"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/etc/fluxd/ssh","name":"git-key"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","serviceAccount":"flux","serviceAccountName":"flux","terminationGracePeriodSeconds":30,"volumes":[{"name":"git-key","secret":{"defaultMode":420,"secretName":"flux-git-deploy"}}]}}}}
  creationTimestamp: null
  generation: 1
  labels:
    name: flux
  name: flux
  selfLink: /apis/extensions/v1beta1/namespaces/cicd/deployments/flux
spec:
  replicas: 1
  selector:
    matchLabels:
      name: flux
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: flux
    spec:
      containers:
      - args:
        - --git-url=git@github.com:jdrahos/kube-manifests.git
        - --git-branch=lga-test
        image: quay.io/weaveworks/flux:1.2.3
        imagePullPolicy: IfNotPresent
        name: flux
        ports:
        - containerPort: 3030
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/fluxd/ssh
          name: git-key
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: flux
      serviceAccountName: flux
      terminationGracePeriodSeconds: 30
      volumes:
      - name: git-key
        secret:
          defaultMode: 420
          secretName: flux-git-deploy
status: {}
