apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: kafka-message-producer-service
  name: kafka-message-producer-service
  selfLink: /api/v1/namespaces/kafka-message-producer/services/kafka-message-producer-service
spec:
  clusterIP: None
  selector:
    app: kafka-message-producer-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
