apiVersion: v1
kind: Service
metadata:
  labels:
    name: kafka-message-producer-service
  name: kafka-message-producer-service
  namspace: kafka-message-producer
spec:
  clusterIP: None
  selector:
    app: kafka-message-producer-app
  sessionAffinity: None
  type: ClusterIP
