apiVersion: v1
data:
  a10url: http://lga-lb01.pulse.prod
  configPrefix: http://lga-configservice.contextweb.prod/ConfigServices_Stage
  dc: lga
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: dc-configs
  selfLink: /api/v1/namespaces/kafka-message-producer/configmaps/dc-configs
