apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"DaemonSet","metadata":{"annotations":{},"labels":{"component":"elasticsearch","role":"data"},"name":"es-data","namespace":"logging"},"spec":{"revisionHistoryLimit":10,"selector":{"matchLabels":{"component":"elasticsearch","role":"data"}},"template":{"metadata":{"annotations":{"pod.alpha.kubernetes.io/init-containers":"[{\"name\":\"sysctl\",\"image\":\"busybox\",\"command\":[\"sysctl\",\"-w\",\"vm.max_map_count=262144\"],\"resources\":{},\"terminationMessagePath\":\"/dev/termination-log\",\"terminationMessagePolicy\":\"File\",\"imagePullPolicy\":\"IfNotPresent\",\"securityContext\":{\"privileged\":true}}]","pod.beta.kubernetes.io/init-containers":"[{\"name\":\"sysctl\",\"image\":\"busybox\",\"command\":[\"sysctl\",\"-w\",\"vm.max_map_count=262144\"],\"resources\":{},\"terminationMessagePath\":\"/dev/termination-log\",\"terminationMessagePolicy\":\"File\",\"imagePullPolicy\":\"IfNotPresent\",\"securityContext\":{\"privileged\":true}}]"},"labels":{"component":"elasticsearch","role":"data"}},"spec":{"containers":[{"args":["-Ecluster.name=es-logging","-Enode.master=false","-Enode.data=true","-Enode.name=${NODE_NAME}","-Ehttp.enabled=true","-Ediscovery.zen.ping.unicast.hosts=elasticsearch-discovery.logging.svc.cluster.local","-Ediscovery.zen.minimum_master_nodes=2"],"command":["/run.sh"],"env":[{"name":"NODE_NAME","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.name"}}},{"name":"ES_JAVA_OPT","value":"-Djava.net.preferIPv4Stack=true -Xms1G -Xmx1G"}],"image":"registry.pulsepoint.com/elasticsearch:5.5.1","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/","port":9200,"scheme":"HTTP"},"initialDelaySeconds":300,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1},"name":"es-data","ports":[{"containerPort":9300,"name":"transport","protocol":"TCP"}],"resources":{"limits":{"cpu":"1","memory":"3Gi"},"requests":{"cpu":"1","memory":"2Gi"}},"securityContext":{"capabilities":{"add":["IPC_LOCK","SYS_RESOURCE"]},"privileged":false},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/data","name":"storage"}]}],"dnsPolicy":"ClusterFirst","initContainers":[{"command":["sysctl","-w","vm.max_map_count=262144"],"image":"busybox","imagePullPolicy":"IfNotPresent","name":"sysctl","securityContext":{"privileged":true},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"nodeSelector":{"es-data":"true"},"restartPolicy":"Always","schedulerName":"default-scheduler","terminationGracePeriodSeconds":30,"volumes":[{"hostPath":{"path":"/var/data/logging"},"name":"storage"}]}},"templateGeneration":4,"updateStrategy":{"type":"OnDelete"}}}
  creationTimestamp: null
  generation: 1
  labels:
    component: elasticsearch
    role: data
  name: es-data
  selfLink: /apis/extensions/v1beta1/namespaces/logging/daemonsets/es-data
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      component: elasticsearch
      role: data
  template:
    metadata:
      annotations:
        pod.alpha.kubernetes.io/init-containers: '[{"name":"sysctl","image":"busybox","command":["sysctl","-w","vm.max_map_count=262144"],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent","securityContext":{"privileged":true}}]'
        pod.beta.kubernetes.io/init-containers: '[{"name":"sysctl","image":"busybox","command":["sysctl","-w","vm.max_map_count=262144"],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent","securityContext":{"privileged":true}}]'
      creationTimestamp: null
      labels:
        component: elasticsearch
        role: data
    spec:
      containers:
      - args:
        - -Ecluster.name=es-logging
        - -Enode.master=false
        - -Enode.data=true
        - -Enode.name=${NODE_NAME}
        - -Ehttp.enabled=true
        - -Ediscovery.zen.ping.unicast.hosts=elasticsearch-discovery.logging.svc.cluster.local
        - -Ediscovery.zen.minimum_master_nodes=2
        command:
        - /run.sh
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: ES_JAVA_OPT
          value: -Djava.net.preferIPv4Stack=true -Xms1G -Xmx1G
        image: registry.pulsepoint.com/elasticsearch:5.5.1
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 9200
            scheme: HTTP
          initialDelaySeconds: 300
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: es-data
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 3Gi
          requests:
            cpu: "1"
            memory: 2Gi
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
            - SYS_RESOURCE
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: storage
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        image: busybox
        imagePullPolicy: IfNotPresent
        name: sysctl
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      nodeSelector:
        es-data: "true"
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /var/data/logging
        name: storage
  templateGeneration: 4
  updateStrategy:
    type: OnDelete
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
