apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: dex
  selfLink: /api/v1/namespaces/kube-system/services/dex
spec:
  clusterIP: <unknown>
  externalTrafficPolicy: Cluster
  ports:
  - name: dexs
    port: 5554
    protocol: TCP
    targetPort: https
  selector:
    app: dex
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
