apiVersion: v1
kind: Service
metadata:
  name: dex
  namespace: kube-system
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: dexs
    port: 5554
    protocol: TCP
    targetPort: https
  selector:
    app: dex
  sessionAffinity: None
  type: NodePort
