apiVersion: v1
kind: Service
metadata:
  labels:
    app: heapster-heapster
    chart: heapster-0.1.1
    heritage: Tiller
    release: heapster
  name: heapster
  namespace: kube-system
spec:
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: heapster-heapster
  sessionAffinity: None
  type: ClusterIP
