apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: heapster-heapster
    chart: heapster-0.1.1
    heritage: Tiller
    release: heapster
  name: heapster
  selfLink: /api/v1/namespaces/kube-system/services/heapster
spec:
  clusterIP: <unknown>
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: heapster-heapster
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
