apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: default
  selfLink: /api/v1/namespaces/kafka-message-producer/serviceaccounts/default
secrets:
- name: default-token-0tqqt
