---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: kubernator
  name: kubernator
  namespace: kubernator
spec:
  replicas: 1
  selector:
    matchLabels:
      run: kubernator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: kubernator
    spec:
      containers:
      - image: smpio/kubernator
        imagePullPolicy: Always
        name: kubernator
        ports:
        - containerPort: 80
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
