apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"prometheus","chart":"prometheus-4.5.0","component":"pushgateway","heritage":"Tiller","release":"prometheus"},"name":"prometheus-prometheus-pushgateway","namespace":"monitoring"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"prometheus","component":"pushgateway","release":"prometheus"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"app":"prometheus","component":"pushgateway","release":"prometheus"}},"spec":{"containers":[{"image":"prom/pushgateway:v0.4.0","imagePullPolicy":"IfNotPresent","name":"prometheus-pushgateway","ports":[{"containerPort":9091,"protocol":"TCP"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/#/status","port":9091,"scheme":"HTTP"},"initialDelaySeconds":10,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":10},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","terminationGracePeriodSeconds":30}}}}
  creationTimestamp: null
  generation: 1
  labels:
    app: prometheus
    chart: prometheus-4.5.0
    component: pushgateway
    heritage: Tiller
    release: prometheus
  name: prometheus-prometheus-pushgateway
  selfLink: /apis/extensions/v1beta1/namespaces/monitoring/deployments/prometheus-prometheus-pushgateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
      component: pushgateway
      release: prometheus
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prometheus
        component: pushgateway
        release: prometheus
    spec:
      containers:
      - image: prom/pushgateway:v0.4.0
        imagePullPolicy: IfNotPresent
        name: prometheus-pushgateway
        ports:
        - containerPort: 9091
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /#/status
            port: 9091
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
